routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});

Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});
/* RUtas de admin  */
Route::get('/admin', function () {
    return view('Administracion.admin');
});
Route::get('/gestionusuario', function () {
    return view('Administracion.gestionusuario');
});
Route::get('/gestion', function () {
    return view('Administracion.gestion');
});
Route::get('/informe', function () {
    return view('Administracion.informe');
});
/* RUtas de admin  */

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('pdf.docencia.tutoria');
});

Route::get('/GestionAcademica', function () {
    return view('pdf.academica.gestionAcademica');
});

Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});


// Route::group(['middleware' => ['role:PTC']], function () {
//     Route::get('/Articulo', function () {
//     return view('pdf.academica.articulo');
// });
// });

Route::get('/Articulo-Revista', function () {
    return view('pdf.academica.Articulo_revista');
});
Route::get('/Articulo-Arbitrado', function () {
    return view('pdf.academica.Articulo_Arbitrado');
});

Route::get('/asesorias', function () {
    return view('pdf.academica.Asesorias');
});

Route::get('/Libro', function () {
    return view('pdf.academica.libro');
});

Route::get('/Informe_tec', function () {
    return view('pdf.academica.informe_tec');
});

Route::get('/Proyecto', function () {
    return view('pdf.academica.proyecto');
});

Route::get('/material', function () {
    return view('pdf.academica.Material');
});

Route::get('/curso', function () {
    return view('pdf.docencia.curso');
});

Route::get('/tutoriaGrupal', function () {
    return view('pdf.docencia.tutoria_grupal');
});

Route::get('/direccionIndividualizada', function () {
    return view('pdf.docencia.direccion_individualizada');
});

Route::get('/estadiaEmpresa', function () {
    return view('pdf.docencia.estadia');
});

Route::get('/cuerpoAcademico', function () {
    return view('pdf.docencia.cuerpo_academico');
});

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF Articulo

Route::group(['middleware' => ['role:PTC']], function () {
    Route::get('/articulo', 'PdfController@pdfFormArticulo');
});
Route::post('pdf_download_Articulo', 'PdfController@pdfDownload_Articulo');

//PDF Material
Route::get('/Material', 'PdfController@pdfFormMaterial');
Route::post('pdf_download_Material', 'PdfController@pdfDownload_Material');

//PDF Asesorias
Route::get('/Asesorias', 'PdfController@pdfFormAsesorias');
Route::post('pdf_download_Asesorias', 'PdfController@pdfDownload_Asesorias');

//PDF Proyecto
Route::get('/proyecto', 'PdfController@pdfFormProyecto');
Route::post('pdf_download_Proyecto', 'PdfController@pdfDownload_Proyectos');

//PDF Revista
Route::get('/Articulo_revista', 'PdfController@pdfFormRevista');
Route::post('pdf_download_Revista', 'PdfController@pdfDownload_Revista');

//PDF Arbitrado
Route::get('/Articulo_Arbitrado', 'PdfController@pdfFormArbitrado');
Route::post('pdf_download_Arbitrado', 'PdfController@pdfDownload_Arbitrado');

//PDF Libro
Route::get('/libro', 'PdfController@pdfFormLibro');
Route::post('pdf_download_Libro', 'PdfController@pdfDownload_Libro');

//PDF Informe
Route::get('/informe_tec', 'PdfController@pdfFormInforme');
Route::post('pdf_download_Informe', 'PdfController@pdfDownload_Informe');

Route::post('pdf_download_Curso', 'PdfController@pdfDownload_Curso');

Route::post('pdf_download_Tutoria', 'PdfController@pdfDownload_Tutoria');

Route::post('pdf_download_Grupal', 'PdfController@pdfDownload_Tutoria_Grupal');

Route::post('pdf_download_Direccion_Individualizada', 'PdfController@pdfDownload_Direccion_Individualizada');

Route::post('pdf_download_Estadia_Empresa', 'PdfController@pdfDownload_Estadia');

Route::post('pdf_download_Cuerpo_Academico', 'PdfController@pdfDownload_CuerpoAcademico');

//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');

//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/fechas','DocumentosController@fechas');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/pasado','DocumentosController@primerAño');
Route::get('/antiguo','DocumentosController@tercerAño');

Route::resource('archivos','DocumentosController');
Route::resource('usuario','UserController');

Auth::routes();

resources/views/Administracion/gestion.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

  <!-- Bootstrap CSS -->
  <div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Historial de documentos</h2>
		        </div>		
	        </div>
		</div>
    </div>
    
	<div class="page-inner mt--5">
    <h1>Buscar Por Año y Periodo</h1>				
             <div class="container">
             <div class="d-flex">
              <!--Filtro Cuatrimestre--->
                  <form action="/fechas" method="GET" class="form-group  col-md-5" >
                    <p>Cuatrimestre:
                    <select class="custom-select border border-secondary" id="inputGroupSelect01"  name="fechas">
                                                  <option value="Enero-Abril">Enero-Abril</option>
                                                  <option value="Mayo-Agosto">Mayo-Agosto</option>     
                                                  <option value="Septiembre-Diciembre">Septiembre-Diciembre</option>   
                                              </select> 
                                              
                    <input type="submit"  class="btn btn-default" value="filtrar"></p>
                    
                </form>
                <!-- Fin de filtro -->
            
            <!--Filtro por año--->
               
                <form action="/fechaActual" style=" left:150px " method="GET"  class="form-group  col-md-5" >
                  <p>Año:  
                   <input type="number" class="form-control border border-secondary" placeholder="filtro por año" min="2017" max="2100" name="fechaActual"> 
                   <input type="submit"  class="btn btn-default" value="filtrar"></p>
    </form>
    <!-- Fin de filtro -->
    </div>
                  </div>  
    <div class="container">
        <div class="table-wrapper table-responsive-lg">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6" style="right:90px" >
                          <table id="dtHorizontalExample" class="table table-striped " >

          <tr>
              <th>#</th>
              <th>Titulo</th>
              <th>Autor</th>
              <th>Tipo de Documento</th>
              <th>Periodo</th>
              <th>Ver</th>
              <th>Descargar</th>
              <th>Fecha de Creacion</th>
              <th>Eliminar</th>
            </tr>
                @foreach ($file as $key=>$data)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$data->titulo}}</td>
                    <td>{{$data->autor}}</td>
                    <td>{{$data->tipo}}</td>
                    <td>{{$data->cuatrimestre}}</td>
                    <td><a class="btn btn-success" href="/files/{{$data->id}}">ver</a></td>
                    <td><a class="btn btn-success" href="/file/download/{{$data->file}}">Descargar</a> </td>
                    <td>{{$data->created_at}}</td>
                    <td>
                        <form action="{{route("archivos.destroy", $data->id)}}" method="POST"> 
                        @method("DELETE")
                        @csrf
                       <input type="submit" class="btn btn-danger" value="Eliminar">
                       </form>
                    </td>
                    </tr>
                @endforeach
      </table>

      
      <div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			       
		        </div>		
	        </div>
		</div>
    </div>

      @endsection

resources/views/Administracion/gestionusuario.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

<!--  Este del formulario inicio de  gestion academida -->
<div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Consulta de usuarios</h2>
		        </div>		
	        </div>
		</div>
    </div>
	<div class="page-inner mt--5">					
<!-- Contenido de Captura de expedientes-->
<!-- Cuadros de menu -->  
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title"></div>
                    </div>
                <div class="card-body">
                <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>
                                   
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Fin de formulario de gestion academida -->



@endsection

resources/views/Administracion/informe.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

  <!--  Este del formulario inicio de  gestion academida -->
<div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Generar</h2>
		        </div>		
	        </div>
		</div>
    </div>
	<div class="page-inner mt--5">					
<!-- Contenido de Captura de expedientes-->
<!-- Cuadros de menu -->  
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Captura de Capacitacion</div>
                    </div>
                <div class="card-body">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6 ">
                                <label for="inputEmail4">Datos x</label>
                                <input type="text" class="form-control border border-secondary" id="inputEmail4" placeholder="Titulo">
                            </div>
                            <div class="form-group col-md-6 ">
                                <label for="inputEmail4">Datos x</label>
                                <input type="text" class="form-control border border-secondary" id="inputEmail4" placeholder="Titulo">
                            </div>
                            <div class="form-group col-md-6 ">
                                <label for="inputEmail4">Datos x</label>
                                <input type="text" class="form-control border border-secondary" id="inputEmail4" placeholder="Titulo">
                            </div>
                            <div class="form-group col-md-6 ">
                                <label for="inputEmail4">Datos x</label>
                                <input type="text" class="form-control border border-secondary" id="inputEmail4" placeholder="Titulo">
                            </div> <div class="form-group col-md-6 ">
                                <label for="inputEmail4">Datos x</label>
                                <input type="text" class="form-control border border-secondary" id="inputEmail4" placeholder="Titulo">
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary">Generar Archivo</button>
                        </form>                                       
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Fin de formulario de gestion academida -->

      @endsection